# Generated by Django 4.2.4 on 2023-08-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_upload', '0002_rename_billparams_billparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billparam',
            name='user',
        ),
        migrations.RemoveField(
            model_name='billupload',
            name='user',
        ),
    ]
