# Generated by Django 4.2.4 on 2023-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_upload', '0004_billparam_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billupload',
            name='bill_file',
            field=models.FileField(upload_to=''),
        ),
    ]
